Repository ScoopInstaller/Versions, pull requests merged in 2021-11, with the labels that each got.

#307 dotnet-sdk-preview: Add the possibility to get RC versions as well
  bucket/dotnet-sdk-preview.json
Labels: review-needed

#308 selenium3: Add version 3.141.59
  bucket/selenium3.json
Labels: review-needed

#291 openrgb: Add nightly
  bucket/openrgb-nightly.json
Labels: review-needed

#314 wox-beta: Fix checkver
  bucket/wox-beta.json
Labels: review-needed

#315 v-weekly: Add version 2021.46
  bucket/v-weekly.json
Labels: review-needed

#273 zig-dev: Add version 0.9.0-dev.1678
  bucket/zig-dev.json
Labels: waiting feedback

#320 beef-nightly: Add version 0.43.1.11182021
  bucket/beef-nightly.json
Labels: review-needed

#321 wezterm-nightly: Add manifest
  bucket/wezterm-nightly.json
Labels: review-needed

#319 linqpad5: Add version 5.44.02
  bucket/linqpad5.json
Labels: review-needed

#322 brave: Add beta and nightly releases
  bucket/brave-beta.json
  bucket/brave-nightly.json
Labels: review-needed

#324 bandizip6: Add version 6.29
  bucket/bandizip6.json
Labels: package-fix-needed

#323 Add GeoGebra 5
  bucket/geogebra5.json
Labels: package-fix-needed

#228 aria2-134: Add last version with SSLv3.0 and TLSv1.0 support.
  bucket/aria2-134.json
Labels: package-fix-needed

#327 postgresql11: add version 11.14
  bucket/postgresql11.json
Labels: package-fix-needed, review-needed
